name: Lint Pull Request

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  lint-backend:
    name: Lint Backend Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
      
      - name: Install dependencies
        working-directory: ./backend
        run: poetry install --no-interaction --no-root
      
      - name: Lint backend with Ruff
        working-directory: ./backend
        run: |
          # Run ruff with auto-fix
          poetry run ruff check --fix .
          
      - name: Check for changes and commit
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Check if there are any changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Auto-fix: Backend linting issues"
            git push
            echo "Changes committed and pushed to source branch"
          else
            echo "No changes to commit"
          fi
          
      - name: Verify all issues are fixed
        working-directory: ./backend
        run: |
          # Run again without --fix to see if there are any issues that couldn't be fixed
          poetry run ruff check . --exit-non-zero-on-fix
  
  lint-frontend:
    name: Lint Frontend Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install
      
      - name: Lint and fix frontend with ESLint
        working-directory: ./frontend
        run: |
          # Attempt to fix issues automatically
          pnpm run lint:fix
      
      - name: Check for changes and commit
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Check if there are any changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Auto-fix: Frontend linting issues"
            git push
            echo "Changes committed and pushed to source branch"
          else
            echo "No changes to commit"
          fi
      
      - name: Verify all issues are fixed
        working-directory: ./frontend
        run: |
          # Run again without fixing to see if there are any issues that couldn't be fixed
          pnpm run lint
